version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4.5
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    ports:
      - 9200
    networks:
      - esnet

  mongo:
    image: 'mongo:3.5.6'
    volumes:
      - './data/db:/data/db'
    networks:
      - esnet
    ports:
      - 27017

  node:
    build: .
    user: 'root'
    environment:
      VIRTUAL_HOST: kbhbilleder.docker
      VIRTUAL_PORT: 9001
    volumes:
      - './:/home/node:cached'
    ports:
      - 9001
    networks:
      - esnet
    links:
      - mongo
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  esnet:
