# This Dockerfile builds the cloud builder image that in turn can build
# development-environment images.
# It expects a checkout of kbhbilleder-docker as its context during build.
FROM buildpack-deps:jessie

RUN apt-get -y update && \
    apt-get -y install \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    apt-key fingerprint 0EBFCD88 && \
    add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable" && \
    apt-get -y update && \
    apt-get -y install docker-ce \
    && rm -rf /var/lib/apt/lists/* # Keeps the image size down

ENV KBH_BILLEDER_BRANCH=master
ENV COLLECTIONS_ONLINE_BRANCH=testing
ENV COLLECTIONS_ONLINE_CUMULUS_BRANCH=master
ENV DOCKER_TAG=latest

# Setup a directory structure much like what we have in kbhbilleder-docker.
# and copy in the files we need from a current checkout of kbhbilleder-docker

WORKDIR /build
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD /entrypoint.sh
